plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

group = mod_group_id
base {
    archivesName = mod_id
}

ext.buildnumber = 0
version = "${mod_version}"

if (System.getenv('GITHUB_RUN_NUMBER')) {
    project.buildnumber = System.getenv('GITHUB_RUN_NUMBER') as Integer
    version = "${mod_version}+${buildnumber}-gha"
}

neoForge {
    version = project.neo_version

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.WARN
            gameDirectory = project.file('run')
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    maven {
        url = 'https://maven.enginehub.org/repo'
        content {
            includeGroupAndSubgroups 'com.sk89q'
            includeGroupAndSubgroups 'org.enginehub'
            includeGroupAndSubgroups 'net.fabricmc'
        }
    }
    maven {
        url = 'https://maven.gegy.dev/releases'
        content {
            includeGroup 'org.lovetropics'
        }
    }
    repositories {
        maven {
            url "https://cursemaven.com"
        }
    }
    mavenLocal()
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

dependencies {
    jarJar(implementation("org.lovetropics:LTLib:$ltlib_version"))

   implementation "curse.maven:worldedit-225608:8037379"
    // There maven jar is broken atm. Using CurseMaven until it's fixed.
//    implementation("com.sk89q.worldedit:worldedit-neoforge-mc$worldedit_mc_version:$worldedit_version") {
//        exclude group: "com.google.guava"
//        exclude group: "org.mozilla"
//    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            worldedit_version_range: worldedit_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata

neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
