modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="ltperms"
version="${file.jarVersion}"
displayName="LoveTropics: Perms"
authors="LoveTropics"
credits=""
description='''
'''

[[dependencies.ltperms]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ltperms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
