modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="ltperms"
version="${file.jarVersion}"
displayName="LoveTropics: Perms"
authors="LoveTropics"
credits=""
description='''
'''

[[dependencies.ltperms]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ltperms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
