modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="ltperms"
version="$mod_version"
displayName="LoveTropics: Permissions"
authors="LoveTropics"
credits=""
description='''
'''

[[dependencies.ltperms]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ltperms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ltperms]]
    modId="worldedit"
    mandatory=true
    versionRange="[7.2,)"
    ordering="NONE"
    side="SERVER"
