modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="ltperms"
version="${file.jarVersion}"
displayName="LoveTropics: Perms"
authors="LoveTropics19"
credits=""
description='''
'''

[[dependencies.ltperms]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.76,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ltperms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
